name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Get commit hash for release
      id: commit
      uses: pr-mpt/actions-commit-hash@v2
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.PAT_TOKEN }}
       
    - name: Build the Docker image and tag it with todays date, also as latest build
      run: |
        docker build . --tag ghcr.io/hsoeren/isitwichtelzeit:latest --tag ghcr.io/hsoeren/isitwichtelzeit:${{ steps.commit.outputs.short }}
        docker push ghcr.io/hsoeren/isitwichtelzeit:${{ steps.commit.outputs.short }}
        docker push ghcr.io/hsoeren/isitwichtelzeit:latest

    - name: Ping webhook
      run: curl -X POST ${{ secrets.DEPLOY_WEBHOOK }}
